# secrets.toml

[gsheet]
  type = "service_account"
  project_id = "connection-404421"
  private_key_id = 
  private_key = """
    -----BEGIN PRIVATE KEY-----
   
    -----END PRIVATE KEY-----
  """
  client_email = "@connection-404421.iam.gserviceaccount.com"
  client_id = " "
  auth_uri = "https://accounts.google.com/o/oauth2/auth"
  token_uri = "https://oauth2.googleapis.com/token"
  auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
  client_x509_cert_url = "
  universe_domain = "googleapis.com"
